import Head from 'next/head'
import Header from '../components/Header'
import Showcase from '../components/Showcase'
import Blog from '../components/Blog'
import About from '../components/About'
import Testimonials from '../components/Testimonials'
import Pricing from '../components/Pricing'
import Footer from '../components/Footer'
export default function Home() {
  return (
    <div id="home">
      <Head>
        <title>NewTown</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> 
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link href="https://fonts.googleapis.com/css2?family=Rubik:wght@400;600;700&display=swap" rel="stylesheet"/>
      </Head>
      {/* Components */}

      <Header />
      <Showcase/>
      <Blog />
      <About />
      <Testimonials />
      <Pricing/>
      <Footer />

      
    </div>
  )
}
